#!/bin/sh

set -x

case `uname` in Darwin*) glibtoolize --automake -c ;;
  *) libtoolize --automake -c ;; esac
aclocal -I m4
autoheader
autoconf
automake -a -c

if test `basename ${0}` = "bootstrap-and-dist" ; then
  ./configure
  make dist-bzip2
fi
    
