#ifndef PARAVERLABELS_H_INCLUDED
#define PARAVERLABELS_H_INCLUDED

#define OLDCFG_LVL_APPL     "appl"
#define OLDCFG_LVL_PTASK    "ptask"
#define OLDCFG_LVL_WORKLOAD "workload"
#define OLDCFG_LVL_TASK     "task"
#define OLDCFG_LVL_THREAD   "thread"
#define OLDCFG_LVL_CPU      "cpu"
#define OLDCFG_LVL_NODE     "node"
#define OLDCFG_LVL_SYSTEM    "system"

#define OLDCFG_LVL_TOPCOMPOSE       "topcompose"
#define OLDCFG_LVL_TOPCOMPOSE1      "topcompose1"
#define OLDCFG_LVL_TOPCOMPOSE2      "topcompose2"
#define OLDCFG_LVL_COMPOSE_WORKLOAD "compose_workload"
#define OLDCFG_LVL_COMPOSE_APPL     "compose_appl"
#define OLDCFG_LVL_COMPOSE_TASK     "compose_task"
#define OLDCFG_LVL_COMPOSE_THREAD   "compose_thread"
#define OLDCFG_LVL_COMPOSE_CPU      "compose_cpu"
#define OLDCFG_LVL_COMPOSE_NODE     "compose_node"
#define OLDCFG_LVL_COMPOSE_SYSTEM   "compose_system"
#define OLDCFG_LVL_COMPOSE1         "compose1"
#define OLDCFG_LVL_COMPOSE2         "compose2"

#define OLDCFG_TAG_WNDW_NAME      "window_name"
#define OLDCFG_TAG_WNDW_TYPE      "window_type"
#define OLDCFG_TAG_WNDW_ID        "window_id"
#define OLDCFG_TAG_WNDW_FACTORS   "window_factors"
#define OLDCFG_TAG_WNDW_POSX      "window_position_x"
#define OLDCFG_TAG_WNDW_POSY      "window_position_y"
#define OLDCFG_TAG_WNDW_WIDTH      "window_width"
#define OLDCFG_TAG_WNDW_HEIGHT      "window_height"
#define OLDCFG_TAG_WNDW_COMM_LINES  "window_comm_lines_enabled"
#define OLDCFG_TAG_WNDW_COLOR_MODE  "window_color_mode"
#define OLDCFG_TAG_WNDW_UNITS     "window_units"
#define OLDCFG_TAG_WNDW_OPERATION "window_operation"
#define OLDCFG_TAG_WNDW_MAXIMUM_Y "window_maximum_y"
#define OLDCFG_TAG_WNDW_MINIMUM_Y "window_minimum_y"
#define OLDCFG_TAG_WNDW_COMPUTE_Y_MAX "window_compute_y_max"
#define OLDCFG_TAG_WNDW_LEVEL     "window_level"
#define OLDCFG_TAG_WNDW_SCALE_RELATIVE "window_scale_relative"
#define OLDCFG_TAG_WNDW_OBJECT "window_object"
#define OLDCFG_TAG_WNDW_IDENTIFIERS "window_identifiers"
#define OLDCFG_TAG_WNDW_BEGIN_TIME "window_begin_time"
#define OLDCFG_TAG_WNDW_STOP_TIME "window_stop_time"
#define OLDCFG_TAG_WNDW_END_TIME "window_end_time"
#define OLDCFG_TAG_WNDW_BEGIN_TIME_RELATIVE "window_begin_time_relative"
#define OLDCFG_TAG_WNDW_NUMBER_OF_ROWS "window_number_of_row"
#define OLDCFG_TAG_WNDW_SELECTED_FUNCTIONS "window_selected_functions"
#define OLDCFG_TAG_WNDW_SEMANTIC_MODULE "window_semantic_module"
#define OLDCFG_TAG_WNDW_COMPOSE_FUNCTIONS "window_compose_functions"
#define OLDCFG_TAG_WNDW_FILTER_MODULE "window_filter_module"
#define OLDCFG_TAG_WNDW_LOGICAL_FILTERED "window_logical_filtered"
#define OLDCFG_TAG_WNDW_PHYSICAL_FILTERED "window_physical_filtered"
#define OLDCFG_TAG_WNDW_FROMTO "window_comm_fromto"
#define OLDCFG_TAG_WNDW_COMM_TAGSIZE "window_comm_tagsize"
#define OLDCFG_TAG_WNDW_TYPEVAL "window_comm_typeval"
#define OLDCFG_TAG_WNDW_OPEN "window_open"
#define OLDCFG_TAG_WNDW_DRAW_MODE "window_drawmode"
#define OLDCFG_TAG_WNDW_DRAW_MODE_ROWS "window_drawmode_rows"
#define OLDCFG_TAG_AN2D_NEW "< NEW ANALYZER2D >"
#define OLDCFG_TAG_AN2D_NAME "Analyzer2D.Name:"
#define OLDCFG_TAG_AN2D_X "Analyzer2D.X:"
#define OLDCFG_TAG_AN2D_Y "Analyzer2D.Y:"
#define OLDCFG_TAG_AN2D_WIDTH "Analyzer2D.Width:"
#define OLDCFG_TAG_AN2D_HEIGHT "Analyzer2D.Height:"

#define OLDCFG_TAG_AN2D_CONTROL_WINDOW "Analyzer2D.ControlWindow:"
#define OLDCFG_TAG_AN2D_DATA_WINDOW "Analyzer2D.DataWindow:"
#define OLDCFG_TAG_AN2D_STATISTIC "Analyzer2D.Statistic:"
#define OLDCFG_TAG_AN2D_CALCULATE_ALL "Analyzer2D.CalculateAll:"
#define OLDCFG_TAG_AN2D_NUM_COLUMNS "Analyzer2D.num_columns:"
#define OLDCFG_TAG_AN2D_HIDE_COLS "Analyzer2D.HideCols:"
#define OLDCFG_TAG_AN2D_SCIENTIFIC_NOTATION "Analyzer2D.scientific_notation:"
#define OLDCFG_TAG_AN2D_NUM_DECIMALS "Analyzer2D.num_decimals:"
#define OLDCFG_TAG_AN2D_THOUSANDSEP "Analyzer2D.thousandsep:"
#define OLDCFG_TAG_AN2D_UNITS "Analyzer2D.units:"
#define OLDCFG_TAG_AN2D_HORIZONTAL "Analyzer2D.HorizVert:"
#define OLDCFG_TAG_AN2D_ACCUMULATOR "Analyzer2D.Accumulator:"
#define OLDCFG_TAG_AN2D_ACCUM_BY_CTRL_WINDOW "Analyzer2D.AccumulateByControlWindow:"
#define OLDCFG_TAG_AN2D_SORTCOLS "Analyzer2D.SortCols:"
#define OLDCFG_TAG_AN2D_SORTCRITERIA "Analyzer2D.SortCriteria:"
#define OLDCFG_TAG_AN2D_PARAMETERS "Analyzer2D.Parameters:"
#define OLDCFG_TAG_AN2D_ANALYSISLIMITS "Analyzer2D.AnalysisLimits:"
#define OLDCFG_TAG_AN2D_RELATIVETIME "Analyzer2D.RelativeTime:"
#define OLDCFG_TAG_AN2D_COMPUTEYSCALE "Analyzer2D.ComputeYScale:"
#define OLDCFG_TAG_AN2D_MINIMUM "Analyzer2D.Minimum:"
#define OLDCFG_TAG_AN2D_MAXIMUM "Analyzer2D.Maximum:"
#define OLDCFG_TAG_AN2D_DELTA "Analyzer2D.Delta:"
#define OLDCFG_TAG_AN2D_COMPUTEGRADIENT "Analyzer2D.ComputeGradient:"
#define OLDCFG_TAG_AN2D_MINIMUMGRADIENT "Analyzer2D.MinimumGradient:"
#define OLDCFG_TAG_AN2D_MAXIMUMGRADIENT "Analyzer2D.MaximumGradient:"
#define OLDCFG_TAG_AN3D_CONTROLWINDOW "Analyzer2D.3D_ControlWindow:"
#define OLDCFG_TAG_AN3D_MINIMUM "Analyzer2D.3D_Minimum:"
#define OLDCFG_TAG_AN3D_MAXIMUM "Analyzer2D.3D_Maximum:"
#define OLDCFG_TAG_AN3D_DELTA "Analyzer2D.3D_Delta:"
#define OLDCFG_TAG_AN3D_FIXEDVALUE "Analyzer2D.3D_FixedValue:"

#define OLDCFG_VAL_DRAW_MODE_LAST       "0"
#define OLDCFG_VAL_DRAW_MODE_MAXIMUM    "1"
#define OLDCFG_VAL_DRAW_MODE_MINNOT0    "2"
#define OLDCFG_VAL_DRAW_MODE_RANDOM     "3"
#define OLDCFG_VAL_DRAW_MODE_RANDOMNOT0 "4"
#define OLDCFG_VAL_DRAW_MODE_AVERAGE    "5"

#define OLDCFG_VAL_COLOR_MODE_GRADIENT  "window_in_gradient_mode"
#define OLDCFG_VAL_COLOR_MODE_NULL_GRADIENT  "window_in_null_gradient_mode"

#define OLDCFG_VAL_TIMEUNIT_NS "Nanoseconds"
#define OLDCFG_VAL_TIMEUNIT_US "Microseconds"
#define OLDCFG_VAL_TIMEUNIT_MS "Milliseconds"
#define OLDCFG_VAL_TIMEUNIT_S  "Seconds"
#define OLDCFG_VAL_TIMEUNIT_M  "Minutes"
#define OLDCFG_VAL_TIMEUNIT_H  "Hours"
#define OLDCFG_VAL_TIMEUNIT_D  "Days"

#define OLDCFG_VAL_FILTER_OBJ_FROM  "from_obj"
#define OLDCFG_VAL_FILTER_OBJ_TO    "to_obj"
#define OLDCFG_VAL_FILTER_COM_TAG   "tag_msg"
#define OLDCFG_VAL_FILTER_COM_SIZE  "size_msg"
#define OLDCFG_VAL_FILTER_COM_BW    "bw_msg"
#define OLDCFG_VAL_FILTER_EVT_TYPE  "evt_type"
#define OLDCFG_VAL_FILTER_EVT_VALUE "evt_value"

#define OLDCFG_VAL_TRUE   "true"
#define OLDCFG_VAL_TRUE2  "True"
#define OLDCFG_VAL_FALSE  "false"
#define OLDCFG_VAL_FALSE2 "False"

#define OLDCFG_VAL_HORIZONTAL "Horizontal"
#define OLDCFG_VAL_VERTICAL   "Vertical"

#define OLDCFG_VAL_SORT_AVERAGE "Average"
#define OLDCFG_VAL_SORT_TOTAL   "Total"
#define OLDCFG_VAL_SORT_MAXIMUM "Maximum"
#define OLDCFG_VAL_SORT_MINIMUM "Minimum"
#define OLDCFG_VAL_SORT_STDEV   "Stdev"
#define OLDCFG_VAL_SORT_AVGDIVMAX "Avg/Max"

#define OLDCFG_VAL_WNDW_TYPE_SINGLE   "single"
#define OLDCFG_VAL_WNDW_TYPE_COMPOSED "composed"

#define OLDCFG_VAL_LIMIT_ALLTRACE  "Alltrace"
#define OLDCFG_VAL_LIMIT_ALLWINDOW "Allwindow"
#define OLDCFG_VAL_LIMIT_REGION    "Region"


// STRING CONSTRUCTION LABELS FOR THE GUI
#define LEVEL_WORKLOAD     "WORKLOAD"
#define LEVEL_APPLICATION  "APPL"
#define LEVEL_TASK         "TASK"
#define LEVEL_THREAD       "THREAD"
#define LEVEL_SYSTEM       "SYSTEM"
#define LEVEL_NODE         "NODE"
#define LEVEL_CPU          "CPU"

static const string LABEL_TIMEUNIT[ DAY + 1 ] =
{
  "ns",
  "us",
  "ms",
  "s",
  "m",
  "h",
  "d"
};

#endif // PARAVERLABELS_H_INCLUDED
